### ISSUE TITLE
How to use PRIuPTR warning-free in Windows?

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#64]
``` C++
LOG_MSG("MODEM: FIFO Overflow! (adds len %" PRIuPTR ")",_len);
```
GCC 32-bit: [warning-free](https://github.com/dreamer/dosbox-staging/commit/c1e10296863b93970b0b31db5ff4f547847e8f25/checks?check_suite_id=335038991#step:8:344)
GCC 64-bit: all of sudden [doesn't know what it is](https://github.com/dreamer/dosbox-staging/runs/326293086#step:8:1711), `warning: unknown conversion type character 'l' in format`

**Comment by krcroft** [comment]
Keith Marshall [says](http://mingw.5.n7.nabble.com/snprintf-and-USE-MINGW-ANSI-STDIO-tp35399p35402.html):
> use appropriate _POSIX_C_SOURCE,
or _XOPEN_SOURCE definitions instead).  This is just evidence of the
inherent dumbness of GCC's printf format warnings.

Ok so we add that #define in `configure.ac`, ensure it's set in `config.h`:
https://github.com/dreamer/dosbox-staging/runs/326387412#step:8:2954
But we still get the warning.

**Comment by krcroft** [comment]
The MinGW forum at Source Forge [mentions](https://sourceforge.net/p/mingw-w64/mailman/message/29128283/):
Use %I64u on Windows, or just use inttypes.h PRIuMAX.

> If you must use %llu, define __USE_MINGW_ANSI_STDIO macro before
including stdio.h. Be aware that if you do this, MS type %I64* format
will no longer work.

So we #define  __USE_MINGW_ANSI_STDIO to 1 in `configure.ac`, and confirm it's set in `config.h` 
https://github.com/dreamer/dosbox-staging/runs/326391973#step:8:2953, but GCC still doesn't recognize the format codes.

We also `#include <inttypes.h> // PRIuPTR` in the same file where we use PRIuPTR:
https://github.com/dreamer/dosbox-staging/blob/44a9fcc4c472eb73ec16d268a01cd5502887ba80/src/hardware/serialport/softmodem.h#L27
But also to no avail.
Why have GCC developers made this so frustrating..argh.

**Comment by krcroft** [comment]
Keith Marshall [says](http://mingw.5.n7.nabble.com/snprintf-and-USE-MINGW-ANSI-STDIO-tp35399p35402.html) that we shouldn't be using __USE_MINGW_ANSI_STDIO:

> This is nothing whatsoever to do with __USE_MINGW_ANSI_STDIO, which you
really SHOULDN'T define yourself, BTW.

And instead says:

> use appropriate _POSIX_C_SOURCE,
or _XOPEN_SOURCE definitions instead.  This is just evidence of the
inherent dumbness of GCC's printf format warnings.

Great! so we #define _POSIX_C_SOURCE to the latest [200809L](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html) specification in `configure.ac`: https://github.com/dreamer/dosbox-staging/blob/44a9fcc4c472eb73ec16d268a01cd5502887ba80/configure.ac#L578

Ensure it's set in `config.h`:
https://github.com/dreamer/dosbox-staging/runs/326387412#step:8:2954
... but GCC still spews  the same unknown format type warnings.

**Comment by krcroft** [comment]
It gets weirder.. https://github.com/grpc/grpc/issues/7703 mentions solving it by _removing_ the -D__USE_MINGW_ANSI_STDIO=1 definition.

So let's try that next.

**Comment by krcroft** [comment]
If GCC really doesn't understand the printf code, then does that mean parsing and expanding the value will be risky or unsafe? 

Otherwise, if the library actually _will_ behave safely and correctly, but this is simply GCC being extra annoying with warnings, then we should very-selectively silence it using a particular `-Wformat` flag specific to just GCC and the 64-bit Windows build.

The other option would be a preprocessor block in `configure.ac` or `config.h` that checks for GCC, 64bit, and Windows: if those are all true then #undef the existing PRIuPTR and redefine it as `%lu`.  However that definition might be fleeting, if downstream `#include <inttypes.h>` simply redefines or overrides PRIuPTR again anyway.  (I haven't tested this.. it's certainly the worst option).

**Comment by dreamer** [comment]
But that switch from autoconf-generated `Bit*` types to `cstdint`-defined types was not merged-in to master yet! (and I don't see it cherry-picked/reimplemented on your branch).

I postponed working on that change until we'll support builds with --enable-debug and without (because --enable-debug brings in so many `format` warnings).

**Comment by dreamer** [comment]
So I hope the problem will disappear after you'll cherry-pick 192487de10b3de7794d61. And hey, while you're cleaning up serialport - feel free to cherry pick addaf4ea0a87a2ce295e35ad5e6cf87b2bc6f299 and 30e65569ad3cde27fd0f2b015031fe49a14b4299 and improve them (I left them half-baked on my wip-warnings branch, because I don't know how to trigger this code in runtime yet).

Overall, about disabling these warnings with `-Wno-format`… For local builds - sure… for CI builds - I would rather not. Most of these warnings indicate, that 64-bit value is formatted as 32-bit value (in various scenarios) - in most cases it's not a big problem (just some log in console might get broken)… But there might be real bugs in there as well.

**Comment by krcroft** [comment]
Cherry picked, re-added one `... %" PRIuPTR "..` format line, and still getting the warning:
```
2019-11-30T01:33:59.9279719Z g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../..  -I../../../include -I/mingw64/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -IC:/tools/msys64/mingw64/include/opus -IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/opus  -Wall -pipe -fstack-protector -fdiagnostics-color=always -g -Og -fno-omit-frame-pointer -mno-ms-bitfields  -MT softmodem.o -MD -MP -MF .deps/softmodem.Tpo -c -o softmodem.o softmodem.cpp
2019-11-30T01:33:59.9292924Z [01m[Ksoftmodem.cpp:[m[K In member function '[01m[Kvoid CSerialModem::EnterIdleState()[m[K':
2019-11-30T01:33:59.9293919Z [01m[Ksoftmodem.cpp:286:12:[m[K [01;35m[Kwarning: [m[Kunknown conversion type character '[01m[Kl[m[K' in format [[01;35m[K-Wformat=[m[K]
2019-11-30T01:33:59.9295753Z   286 |    LOG_MSG([01;35m[K"Serial%" PRIuPTR ": Modem could not open TCP port %" PRIuPTR "."[m[K,
2019-11-30T01:33:59.9344087Z       |            [01;35m[K^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
2019-11-30T01:33:59.9362337Z [01m[Ksoftmodem.cpp:286:12:[m[K [01;35m[Kwarning: [m[Kunknown conversion type character '[01m[Kl[m[K' in format [[01;35m[K-Wformat=[m[K]
2019-11-30T01:33:59.9374670Z [01m[Ksoftmodem.cpp:286:12:[m[K [01;35m[Kwarning: [m[Ktoo many arguments for format [[01;35m[K-Wformat-extra-args[m[K]
```

**Comment by krcroft** [comment]
Will pull in your WIP commits too - nice clean up there! I've been testing what I can connecting to various telnet BBSs, but haven't been able to exercise BUSY or NOANSWER (code = 8). 

Regarding the warning - Yes, I'd also rather see that the compiler doesn't understand something than hide it; we just need to figure out how to enable that syntax under 64-bit GCC.

**Comment by dreamer** [comment]
I'll reboot to Windows later and try to reproduce it on my local machine. We can't rule out gcc in msys2 being misconfigured somehow… (hopefully that's not it). Hey, if you could describe what you use to trigger connect to BBS from within DOSBox I would be grateful :)

**Comment by krcroft** [comment]
It's really slick how it works:
1. Enable a COM port (I use the first) in your conf:
``` ini
[serial]
serial1=modem listenport:45000
```
Listen is not critical, however if you omit it tries to listen on port 23, which fails unless you're running as root.

1. Then configure your terminal program to use COM1; leave the default port and interrupt as-is (I'm not even sure if these really matter).
1. Add a new BBS to your dialer, and enter the hostname instead of the phone number.
1. If the site is listening on something other than port 23, append `:$port` to the hostname `remote.bbs.org:1023` for example.
![2019-11-29_18-40](https://user-images.githubusercontent.com/1557255/69894750-dd1b2100-12d8-11ea-994b-bdf5f3356140.png)
![2019-11-29_18-42](https://user-images.githubusercontent.com/1557255/69894751-e1473e80-12d8-11ea-9115-9f076c412278.png)

**Comment by krcroft** [comment]
Downloading from a BBS using something like ZModem won't work through, because some characters seem to get eaten or lost; so the download tool will endless retry/re-sync/timeout.

To work-around it, you can directly "wire" your serial port to a hard-coded host, like this:

`serial1=nullmodem server:tfb-bbs.org telnet:1 usedtr:1`

When your terminal program opens, it will detect that COM 1 is already active, and your BBS session will already be underway.  Unfortunately though it will be black-and-white without having negotiated an upgraded terminal/ANSI set.  None the less, you can still browse and downloads will run clean:

![2019-11-29_19-34](https://user-images.githubusercontent.com/1557255/69895173-fffd0380-12df-11ea-8e8b-cae0b8becade.png)

**Comment by dreamer** [comment]
I wrote small test program and compiled it in MSYS2, and it worked, but...

```
#include <cstdio>
#include <cstdint>
#include <inttypes.h>

using Bitu = uintptr_t;

int main()
{
	const Bitu x = 42;
	printf("%zu %zu %" PRIuPTR "\n", sizeof(&x), sizeof(x), x);
	return 0;
}
```

```
dreamer_@tars MSYS ~/msys-cstdint-test
$ g++ -std=c++11 test.cpp

dreamer_@tars MSYS ~/msys-cstdint-test
$ ./a.exe
8 8 42

dreamer_@tars MSYS ~/msys-cstdint-test
$ file a.exe
a.exe: PE32+ executable (console) x86-64, for MS Windows
```
So it defaults to 64-bit, builds correctly, and works... so now I am confused. Seems like a problem caused by autotools to me - I'll try to reproduce via local build of dosbox-staging.

**Comment by krcroft** [comment]
Does `-Wall` complain?

**Comment by dreamer** [comment]
D'oh! Of course.

But even with `-Wall`, it still compiles. And one more good news: I used `PRIu8` in my WIP SDL2 branch ([po/boxtron-test-5-1](https://github.com/dreamer/dosbox-staging/tree/po/boxtron-test-5-1)) - it didn't work at first, but when I fixed include order, it worked on all Windows builds! So maybe add `cinttypes` specifically to the file that has a problem - maybe it's another case of bad include ordering.

**Comment by krcroft** [comment]
Tried include at the top:
https://github.com/dreamer/dosbox-staging/commit/5256662ed5ce11eed46e211aefc308da36fb9acf

But no-go:
https://pipelines.actions.githubusercontent.com/RDKYnb9yFkXPfcXINdFWH3mzDaNqlgzrXM4kV8rnx6PJBbLLEF/_apis/pipelines/1/runs/2634/signedlogcontent/9?urlExpires=2019-12-01T17%3A35%3A16.5500362Z&urlSigningMethod=HMACV1&urlSignature=1FEnU00pUDlizsAIc5z8R1HsqXD2Dn24LVI5KOuP2o8%3D

```
2019-12-01T17:33:03.2914283Z g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../..  -I../../../include -I/mingw64/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -IC:/tools/msys64/mingw64/include/opus -IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/opus  -Wall -pipe -fstack-protector -fdiagnostics-color=always -g -Og -fno-omit-frame-pointer -mno-ms-bitfields  -MT softmodem.o -MD -MP -MF .deps/softmodem.Tpo -c -o softmodem.o softmodem.cpp
2019-12-01T17:33:03.2925948Z [01m[Ksoftmodem.cpp:[m[K In member function '[01m[Kvoid CSerialModem::EnterIdleState()[m[K':
2019-12-01T17:33:03.2938809Z [01m[Ksoftmodem.cpp:289:12:[m[K [01;35m[Kwarning: [m[Kunknown conversion type character '[01m[Kl[m[K' in format [[01;35m[K-Wformat=[m[K]
2019-12-01T17:33:03.2940398Z   289 |    LOG_MSG([01;35m[K"Serial%" PRIuPTR ": Modem could not open TCP port %" PRIuPTR "."[m[K,
2019-12-01T17:33:03.2978977Z       |            [01;35m[K^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
2019-12-01T17:33:03.2985221Z [01m[Ksoftmodem.cpp:289:12:[m[K [01;35m[Kwarning: [m[Kunknown conversion type character '[01m[Kl[m[K' in format [[01;35m[K-Wformat=[m[K]
2019-12-01T17:33:03.3005951Z [01m[Ksoftmodem.cpp:289:12:[m[K [01;35m[Kwarning: [m[Ktoo many arguments for format [[01;35m[K-Wformat-extra-args[m[K]
```
Wil try with include at the bottom of the block next.

**Comment by dreamer** [comment]
Hmm, can you test with a different formatting string, that should work as well? e.g. `uint32_t` / `PRIu32`?

**Comment by krcroft** [comment]
> Hmm, can you test with a different formatting string, that should work as well? e.g. `uint32_t` / `PRIu32`?

That was it! `PRIu32` compiles warning-free but PRIuPTR does not.  

It looks like the latter is incorrectly expanded to "l" instead of "lu", so maybe the "fix" is to make this change in GCC's header (and report it upstream).

**Comment by krcroft** [comment]
Here's GCC's header on 64-bit MSYS2:
```
2019-12-01T19:27:45.1769848Z /* 7.8.1 Macros for format specifiers
2019-12-01T19:27:45.1769953Z  * 
2019-12-01T19:27:45.1770060Z  * MS runtime does not yet understand C9x standard "ll"
2019-12-01T19:27:45.1770175Z  * length specifier. It appears to treat "ll" as "l".
2019-12-01T19:27:45.1770294Z  * The non-standard I64 length specifier causes warning in GCC,
2019-12-01T19:27:45.1770416Z  * but understood by MS runtime functions.
2019-12-01T19:27:45.1770896Z  */
2019-12-01T19:27:45.1771004Z #if defined(_UCRT) || __USE_MINGW_ANSI_STDIO
2019-12-01T19:27:45.1771111Z #define PRId64 "lld"
2019-12-01T19:27:45.1771213Z #define PRIi64 "lli"
2019-12-01T19:27:45.1771312Z #define PRIo64 "llo"
2019-12-01T19:27:45.1771413Z #define PRIu64 "llu"
2019-12-01T19:27:45.1771513Z #define PRIx64 "llx"
2019-12-01T19:27:45.1771612Z #define PRIX64 "llX"
2019-12-01T19:27:45.1771711Z #else
2019-12-01T19:27:45.1771810Z #define PRId64 "I64d"
2019-12-01T19:27:45.1771914Z #define PRIi64 "I64i"
2019-12-01T19:27:45.1772130Z #define PRIo64 "I64o"
2019-12-01T19:27:45.1772232Z #define PRIu64 "I64u"
2019-12-01T19:27:45.1772334Z #define PRIx64 "I64x"
2019-12-01T19:27:45.1772435Z #define PRIX64 "I64X"
2019-12-01T19:27:45.1772533Z #endif
2019-12-01T19:27:45.1772579Z 

2019-12-01T19:27:45.1794777Z #ifdef _WIN64
2019-12-01T19:27:45.1794923Z #define PRIdPTR PRId64
2019-12-01T19:27:45.1795049Z #define PRIiPTR PRIi64
2019-12-01T19:27:45.1795191Z #define PRIoPTR PRIo64
2019-12-01T19:27:45.1795318Z #define PRIuPTR PRIu64
2019-12-01T19:27:45.1795446Z #define PRIxPTR PRIx64
2019-12-01T19:27:45.1795583Z #define PRIXPTR PRIX64
2019-12-01T19:27:45.1795714Z #define SCNdPTR PRId64
2019-12-01T19:27:45.1795852Z #define SCNiPTR PRIi64
2019-12-01T19:27:45.1795994Z #define SCNoPTR PRIo64
2019-12-01T19:27:45.1796123Z #define SCNxPTR PRIx64
2019-12-01T19:27:45.1796249Z #define SCNuPTR PRIu64
2019-12-01T19:27:45.1796371Z #else
2019-12-01T19:27:45.1796498Z #define PRIdPTR "d"
2019-12-01T19:27:45.1796626Z #define PRIiPTR "i"
2019-12-01T19:27:45.1796754Z #define PRIoPTR "o"
2019-12-01T19:27:45.1796883Z #define PRIuPTR "u"
2019-12-01T19:27:45.1797088Z #define PRIxPTR "x"
2019-12-01T19:27:45.1797226Z #define PRIXPTR "X"
2019-12-01T19:27:45.1797352Z #define SCNdPTR "d"
2019-12-01T19:27:45.1797480Z #define SCNiPTR "i"
2019-12-01T19:27:45.1797605Z #define SCNoPTR "o"
2019-12-01T19:27:45.1797731Z #define SCNxPTR "x"
2019-12-01T19:27:45.1797858Z  #define SCNuPTR "u"
2019-12-01T19:27:45.1797990Z #endif
```

Knowing that's we're getting the `%l` scenario, I undefined `_UCRT` and `__USE_MINGW_ANSI_STDIO` to try to get this `#define PRIu64 "I64u"` instead of `#define PRIu64 "llu"`.. but it still isn't working, and getting `%l`.

I'm going to try redefining PRIuPTR to %lu at the end of our "types.h", and see if that takes effect.

**Comment by krcroft** [comment]
Ok - I added this to `types.h`:

``` C++
#include <cinttypes>
#include <cstdint>

/* Work around this bug in /mingw64/x86_64-w64-mingw64/include/inttypes.h:
 * MS runtime does not yet understand C9x standard "ll"
 * length specifier. It appears to treat "ll" as "l".
 * The non-standard I64 length specifier causes warning in GCC,
 * but understood by MS runtime functions.
 */
#if defined(WIN64) && defined(__MINGW64__) && defined(__GNUC__) && !defined(__clang__)
#ifdef PRIuPTR
#undef PRIuPTR
#endif
#define PRIuPTR "I64u"
#endif
```

And am careful to /not/ re-include <cinttypes> or <cstdint> in softmodem.cpp, however despite this I'm still getting:

```
2019-12-01T20:32:51.1344874Z g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../..  -I../../../include -I/mingw64/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -IC:/tools/msys64/mingw64/include/opus -IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/opus  -Wall -pipe -fstack-protector -fdiagnostics-color=auto -g -Og -fno-omit-frame-pointer -mno-ms-bitfields  -MT softmodem.o -MD -MP -MF .deps/softmodem.Tpo -c -o softmodem.o softmodem.cpp
2019-12-01T20:32:51.1355356Z softmodem.cpp: In member function 'void CSerialModem::EnterIdleState()':
2019-12-01T20:32:51.1388014Z softmodem.cpp:288:12: warning: unknown conversion type character 'l' in format [-Wformat=]
2019-12-01T20:32:51.1389483Z   288 |    LOG_MSG("Serial%" PRIuPTR ": Modem could not open TCP port %" PRIuPTR ".",
2019-12-01T20:32:51.1436100Z       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-01T20:32:51.1460530Z softmodem.cpp:288:12: warning: unknown conversion type character 'l' in format [-Wformat=]
2019-12-01T20:32:51.1474031Z softmodem.cpp:288:12: warning: too many arguments for format [-Wformat-extra-args]
```

Slowly losing my mind with this.

**Comment by krcroft** [comment]
Now let's try putting this block after all the `#include`s in softmode.cpp:
``` C++
#if defined(WIN64) && defined(__MINGW64__) && defined(__GNUC__) && !defined(__clang__)
#ifdef PRIuPTR
#undef PRIuPTR
#endif
#define PRIuPTR "I64u"
#endif
```
If this doesn't do it.. then I give up :man_shrugging:

**Comment by krcroft** [comment]
Still didn't solve it. 
``` C++
IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/opus  -Wall -pipe -fstack-protector -fdiagnostics-color=auto -g -Og -fno-omit-frame-pointer -mno-ms-bitfields  -MT softmodem.o -MD -MP -MF .deps/softmodem.Tpo -c -o softmodem.o softmodem.cpp
2019-12-01T20:48:28.7561346Z softmodem.cpp: In member function 'void CSerialModem::EnterIdleState()':
2019-12-01T20:48:28.7567137Z softmodem.cpp:295:12: warning: unknown conversion type character 'l' in format [-Wformat=]
2019-12-01T20:48:28.7600907Z   295 |    LOG_MSG("Serial%" PRIuPTR ": Modem could not open TCP port %" PRIuPTR ".",
2019-12-01T20:48:28.7677991Z       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-01T20:48:28.7729574Z softmodem.cpp:295:12: warning: unknown conversion type character 'l' in format [-Wformat=]
2019-12-01T20:48:28.7736289Z softmodem.cpp:295:12: warning: too many arguments for format [-Wformat-extra-args]
2019-12-01T20:48:28.7757240Z make[4]: Leaving directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
2019-12-01T20:48:28.7940819Z make[4]: Entering directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
2019-12-01T20:48:28.7950244Z mv -f .deps/softmodem.Tpo .deps/softmodem.Po
```
Maybe my pre-processor block is too restrictive and isn't being met.. time to try more.

**Comment by krcroft** [comment]
Getting somewhere!
The relaxed criteria worked: `#if defined(__MINGW64__) && !defined(__clang__)` and using `#define PRIuPTR "I64u"` is warning-free.
Going to move this back into `types.h` and see if it still holds.

**Comment by krcroft** [comment]
That did it! Finally a warning-free compile with `#define PRIuPTR "I64u"` re-defined in `types.h`.
```
2019-12-01T21:12:04.7986545Z g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../..  -I../../../include -I/mingw64/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -IC:/tools/msys64/mingw64/include/opus -IC:/tools/msys64/mingw64/include -IC:/tools/msys64/mingw64/include/opus  -Wall -pipe -fstack-protector -fdiagnostics-color=auto -g -Og -fno-omit-frame-pointer -mno-ms-bitfields  -MT softmodem.o -MD -MP -MF .deps/softmodem.Tpo -c -o softmodem.o softmodem.cpp
2019-12-01T21:12:04.7996121Z make[4]: Leaving directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
2019-12-01T21:12:04.8297293Z make[4]: Entering directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
2019-12-01T21:12:04.8305341Z mv -f .deps/softmodem.Tpo .deps/softmodem.Po
2019-12-01T21:12:04.8314378Z make[4]: Leaving directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
2019-12-01T21:12:05.4935049Z make[4]: Entering directory '/d/a/dosbox-staging/dosbox-staging/src/hardware/serialport'
```
